### ISSUE TITLE
Deployment - NPM

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#16]
For the Polykey CLI prototype, we want this to be NPM installable. So NPM is our first deployment target. Later we'll add more deployment paths, and this will need to be automated into our CI/CD to distribute these packages automatically.

**Comment by robert-cronin** [comment]
The CLI (which is included with [js-polykey](https://www.npmjs.com/package/js-polykey)) is now deployed via npm. Automatic deployment is still yet to be added, but I think for now it can be manually deployed and I will create a new issue for automatic deployment.
