### ISSUE TITLE
Installation Procedure

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#19]
Upon installation the command `polykey` will be made available to the `PATH`. This allows them to run the `polykey` command on their terminal.

Upon the initial run of `polykey`:

1. Optional installation of the short alias `pk` (alias is really just something that can be added to the shell or as an additional symlink).
2. Specification of the location of keynode state.
3. Creation of the keynode public and private keypair.
4. Detection/installation of the agent (the agent may need to be installed alternatively in some OSes like Linux)

**Comment by robert-cronin** [comment]
points 1 and 4 are completed upon installation from our overlay (or possibly nixpkgs in the future) and points 2 and 3 are moved to the running of the app. That is to say creation of new keynodes and location specification of existing keynodes will be the domain of the app and not the installation procedure.

**Comment by CMCDragonkai** [comment]
One has to differentiate between the GUI and CLI.

Because when someone use the CLI most likely they want to use the CLI version, we could do something like:

```
polykey # calls CLI
pk # calls CLI
polykey-gui # launches GUI/calls GUI
```

Or some other variation.

**Comment by CMCDragonkai** [comment]
Or `polykey` calls GUI while `pk` calls CLI.

**Comment by CMCDragonkai** [comment]
I'm imagining what would happen if someone uses Nix to install js-polykey and then also installs polykey.

You would end up with both, so then 2  separate commands.

However the GUI polykey package should also install the CLI command since it includes it, so users should only really install one or the other.
