### ISSUE TITLE
Define Relevant User Metrics

### ISSUE THREAD

**Issue by mariafoo** [MatrixAI/Polykey-Desktop#24]
To obtain user metrics, we can ask users to send diagnostics to us. This may be an opt-in/opt-out system. We can detail what kind of diagnostics we will be collecting.

**Comment by CMCDragonkai** [comment]
The cool thing about it being a p2p network is that we can get metrics automatically by oberving the network.

On 16 April 2019 17:31:49 GMT+10:00, Maria Foo <notifications@github.com> wrote:
>To obtain user metrics, we can ask users to send diagnostics to us.
>This may be an opt-in/opt-out system. We can detail what kind of
>diagnostics we will be collecting. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/PolyKey/issues/24

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
I've renamed this as before, because this issue actually is about that. But I think this is low priority.

**Comment by CMCDragonkai** [comment]
Since this is decentralized application, we would need to request the user's permission to send back diagnostic information back to home. Since this is low priority for now, closing it.
