### ISSUE TITLE
Establish relationship between Human digital identities and Keynode clusters

### ISSUE THREAD

**Issue by mariafoo** [MatrixAI/Polykey-Desktop#25]
One user may have multiple keynodes per device and across devices. A method to assign these keynodes to one user is required for the user to easily manage their keynodes (e.g. synchronisation or file management).

**Comment by CMCDragonkai** [comment]
Keynodes aren't really "assigned" to users. Users create keynodes, and then we can establish a link between keynodes and a human digital identity.

**Comment by CMCDragonkai** [comment]
#2 details how GPG manages human digital identities via their primary key and subkey systems. Especially important as humans take on different personas depending on their environment. Like private identity vs work identity, and in turn means we have different sets of secrets we manage for each persona as well.

**Comment by CMCDragonkai** [comment]
@robert-cronin Please talk about here what I mentioned about X.509 certificates and how they represent a "signed" link between a virtual identity "the key" and physical identities "name, address... etc".

**Comment by robert-cronin** [comment]
As mentioned above, there is an issue of linking of a keynode cluster to a particular physical identity, how does a third party (or the keynode cluster even) know that a keynode is linked to that identity?  Previous discussion mentioned a certificate authority (CA) as a way that the two can be linked.

In comes the X.509 standard, it defines the format of pub key certificates. It is what is used in TLS/SSL to confirm the identity of websites.

X.509 certificates can be the "signed" link between the pub key and the physical identity. The polykey workflow might go something like this, a person (i.e. the physical 
 identity) first generates a key pair (i.e. virtual identity) and uses the generated public key to sign a CSR (certificate signing request) to the CA (see PKI.js below) which contains information about the physical identity (e.g. name, email address, etc) as well as the distinguished name (DN) that the certificate is signed for (in this case, our DN would be a reference to a keynode cluster)

One question is how would we implement the CA? One way we can support CA activities is using [PKI.js](https://pkijs.org/). It can be used to vett the certificates and is able to work with X.509 certs out of the box.

**Comment by robert-cronin** [comment]
We now have a gRPC server that relies on CA certs in the [js-polykey](https://github.com/MatrixAI/js-polykey) lib. The plan is to have a mechanism in js-polykey to support arbitrary CA's so it's up to this repo to implement the interaction CA. This depends on an existing CA that is hosted at a specific domain and the root certs of which can be passed into `js-polykey` 

There is also the idea of having each polykey node act as its own CA, but this will be more specific to the `js-polykey` lib.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
