### ISSUE TITLE
Secret Management - Reuse Unix Commands to Manage Filesystems

### ISSUE THREAD

**Issue by mariafoo** [MatrixAI/Polykey-Desktop#28]
We can reuse commands like `cp` and `mv`, but that expects target filesystems. An alternative idea is to `import` files.

**Comment by CMCDragonkai** [comment]
Superseded by #26. I've decided to discard the import command since it's possible to have this with unix style subcommands. The only problem is that you don't have an import stage and then within secret storage stage. It's all meshed with the real filesystem all at the same time.
