### ISSUE TITLE
Vaults - Version History

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#31]
TBD

**Comment by CMCDragonkai** [comment]
@gideonairex can you expand on this issue with a few sketches on this idea. Would be important to make sure we have this figured out before we expend more time on designing the vault interface.

**Comment by faithveloro** [comment]
![View My Vaults - View Details](https://user-images.githubusercontent.com/46587577/102579898-6c8bb000-4138-11eb-96ef-a3d9ca365208.jpg)

Something I drafted yesterday for history @CMCDragonkai @gideonairex

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
