### ISSUE TITLE
File Integrity and Backups

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#32]
We probably want to ensure some level of integrity with out secrets and avoid overwriting data when we discover something has gone wrong so it is possible to recover the data. Need to spec this out more.

**Comment by CMCDragonkai** [comment]
Relevant:

* https://github.com/MatrixAI/js-encryptedfs/issues/11
* https://github.com/MatrixAI/js-polykey/issues/10

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
