### ISSUE TITLE
Port codebase to Typescript

### ISSUE THREAD

**Issue by MeanMangosteen** [MatrixAI/Polykey-Desktop#33]
The codebase currently utilises flow type annotations. We want to migrate to the more modern typescript for Polykey. This isn't a big chunk of work since, the code base isn't too large at this point.

**Comment by MeanMangosteen** [comment]
I had some trouble importing EncryptedFS into Polykey which is now using  typescript. EFS already had flow type annotations which typescript interpreted as typescript annotations and so the modules weren't integrating nicely with each other. At this stage it seemed better just to port efs over. TS seems to be a lot more strict and thorough than flow, there where a few hiccups in getting all types compatible with external modules, but as of a630013 the code base (including efs) has been ported to typescript.

**Comment by CMCDragonkai** [comment]
Does this end up extending to VFS as well? I'd prefer to not need to port that to typescript as well.

**Comment by MeanMangosteen** [comment]
Since I'm using not vfs as extensively, I've just had it to ignore the types in vfs.

**Comment by CMCDragonkai** [comment]
VFS doesn't export any types, as the flow is completely internal, so it would just be like an untyped JS object when used by EFS probably.

**Comment by MeanMangosteen** [comment]
For any module you import in typescript you have to have a declaration file for the types. So for VFS I just have an empty file while for other I get it from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)  Then that's more likely the case. I don't get any type information or checking when I'm accessing vfs.

**Comment by CMCDragonkai** [comment]
Ok that's good for now then.

**Comment by CMCDragonkai** [comment]
What else needs to be done for this issue to be closed?

**Comment by MeanMangosteen** [comment]
Nothing, this will be closed in the upcoming PR.

**Comment by CMCDragonkai** [comment]
@robert-cronin This is now assigned to you. But this is in the Polykey repo not in js-encryptedfs. We can have separate issues for each repository.
