### ISSUE TITLE
PolyKey Nativescript Multi-threading Model

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#39]
An inital **async architecture** has been settled on in js-encryptedfs in [issue 4](https://github.com/MatrixAI/js-encryptedfs/issues/4). This relies on webworkers via [threads.js](https://github.com/andywer/threads.js/).

In nativescript, however, we would like to rely on nativescript's inbuilt [multi-threading model](https://docs.nativescript.org/core-concepts/multithreading-model) for mobile clients. This comes with certain limitations, the main one being an inability to serialize objects to send between worker contexts. In threads.js, this is easy with [Transferable Objects](https://threads.js.org/usage-advanced#transferable-objects). 

It might be possible in nativescript author our own memory sharing and pass Buffers by reference but it still remains to be seen if this is possible. If we can't transfer objects in nativescript, we might have to just serialize the buffers accept a performance hit.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
