### ISSUE TITLE
Nativescript file system as an EFS lowerDir

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#40]
We have built EFS as an isomorphic library which means byo lower file system but we have modelled the lower file system on what is available with the nodejs fs module. This might be a concern when building the PolyKey app in nativescript. Research needs to be done on whether or not the nativescript [file-system](https://docs.nativescript.org/api-reference/modules/_file_system_) module can be directly plugged into EFS as a lower directory or how an interface between these two might look like.

**Comment by CMCDragonkai** [comment]
It probably cannot, so we'll need to adapt it. Should be easy though. Just exception whenever there's an unimplementable operation. Primarily we will work on streams and chunks, chunks can be based on fd seeking or on memory mapping.

On 12 May 2020 14:04:44 GMT+10:00, Robbie Cronin <notifications@github.com> wrote:
>We have built EFS as an isomorphic library which means byo lower file
>system but we have modelled the lower file system on what is available
>with the nodejs fs module. This might be a concern when building the
>PolyKey app in nativescript. Research needs to be done on whether or
>not the nativescript
>[file-system](https://docs.nativescript.org/api-reference/modules/_file_system_)
>module can be directly plugged into EFS as a lower directory or how an
>interface between these two might look like.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/PolyKey/issues/40

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
