### ISSUE TITLE
QR code for public key sharing

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#41]
Just in case there are key-nodes no attached to human identities on keybase, we might be able to encode the public key in a QR code for easy scanning. This is a low priority once we get keybase integration in thought.

For example this is my keybase public key encoded in a pretty huge QR code, but it does seem to scan properly.
![image](https://user-images.githubusercontent.com/8540764/83745553-4a48ae00-a690-11ea-8116-2897a2fc1550.png)
The quality seems to have reduced when uploading to github, I used this website for encoding: https://www.the-qrcode-generator.com/
There are other QR code formats we could look into.

**Comment by CMCDragonkai** [comment]
Given that we are thinking of cryptoforts avatars for Polykey, I wonder if they can be used instead of QR codes.

For higher density QR codes, we can use fountain codes combined with animation and colours.

See: https://github.com/divan/txqr

**Comment by CMCDragonkai** [comment]
We should have a general issue for the Keynode Profile.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
