### ISSUE TITLE
Redux vs. Vuex for use in Vue.js

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#42]
Vuex is a state management library similar to Redux and this issue is for documenting the differences in the two and deciding which is the best for the PolyKey app.

[Here](https://www.codementor.io/@petarvukasinovic/redux-vs-vuex-for-state-management-in-vue-js-n10yd7g2f) are some notes along this line from [codementor.io](codementor.io)

The main difference is that Vuex mutates the state as opposed to Redux making it immutable. From the vuejs [documentation](https://vuejs.org/v2/guide/state-management.html), Redux can be used with Vue.js just fine via a package [redux-vue](https://classic.yarnpkg.com/en/package/redux-vue). The question is what advantage is there to adopting Vuex?

It also looks like Vuex optimises for the Vuejs components and is claimed to be a little more efficient than Redux within Vuejs. I will have further information after I try an experiment with Vuex within the PolyKey Electron app.

**Comment by CMCDragonkai** [comment]
Once you have the experiment done, please post notes up here, and link the PR.

But also... I like using the redux debugger on Chrome. Does vue have something similar? One of the reasons we can continue using redux.

**Comment by robert-cronin** [comment]
Yes, Vuex has a dedicated tab on the [Vuejs devtools extension](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en)

**Comment by CMCDragonkai** [comment]
In the past, when using Redux, I always paired it up with immutable. Which is pretty cool and useful, but I realised for a lot of things, it was quite heavyweight. So nowadays I recommend going for https://github.com/immerjs/immer first. And only use immutablejs if you really need a persistent advanced data structure, and then finally reaching for a proper database like datascript when you need advanced indexing.

But you can get really far with just "immer" lists and objects.

So if we use redux with immer it should just be fine?

**Comment by CMCDragonkai** [comment]
Please also find out what the equivalent to react hooks are in Vue.

**Comment by CMCDragonkai** [comment]
Also really important are things like memoize or the react combinators that "cache" things. That was one of the issues with React and Redux, trying to minimize the amount of unnecessary re-renders. One had to explicitly indicate this in some cases.

**Comment by robert-cronin** [comment]
Hooks came to VueJS in version 3: https://blog.logrocket.com/hooks-are-coming-to-vue/
So in react you can `useState(...)` and in VueJS you can just `useData(...)`

**Comment by robert-cronin** [comment]
I've created a crude example on the `redux-vs-vuex` branch with what I could scrape from the internet. It was quite challenging to get redux to work similar to vuex with all it's `getters` and nice integration into vuejs. I followed this example project: https://codesandbox.io/s/ywr3vpzxnz?file=/webpack.config.js

**Comment by robert-cronin** [comment]
From the ongoing development in this repo, it seems to me that vuex would be the stronger candidate. It fits in quite well with the components, minimal configuration and has much of the same middleware that redux has in the form of plugins. This issue should be solved in the upcoming PR #43
