### ISSUE TITLE
Polykey should be GPL

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#46]
While js-polykey is APL2, the GUI Polykey can be GPL.

I think it was originally GPL, but it might have been overwritten from the recent merge.

And if this repo is GPL, then the components can also be GPL for now. I'm still trying to figure out how to ensure the branding is maintained, so we'll figure that out later.

**Comment by robert-cronin** [comment]
License change has been pushed to master. Closing.
