### ISSUE TITLE
Use upstream nixpkgs for pkgs.nix because this is opensource

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#47]
Change pkgs.nix an upstream nixpkgs pin. You already have this in release.nix, just move that over to pkgs.nix.

```
with import ( builtins.fetchGit {
  url = "https://github.com/nixos/nixpkgs-channels/";
  rev = "dcb64ea42e64aaecd8e6fef65cc86245c9666818";
}) {};
```

Also we won't have any dependencies here that we need that won't be in upstream yet.

But if we do... we will then have an opensource overlay.

**Comment by robert-cronin** [comment]
Yeah I like the idea of an opensource overlay to complement our open source projects.

**Comment by robert-cronin** [comment]
This has been pushed to master.
