### ISSUE TITLE
Windows and Mac CI/CD - for integration testing and building

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#48]
Gitlab now supports Windows CI/CD: https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/

Although we may not need the Windows CI/CD to build our electron application, the CI/CD is still essential to run integration tests.

Mac CI/CD on gitlab.com is underway:

* https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/5720
* https://gitlab.com/gitlab-org/gitlab/-/issues/224124
* https://about.gitlab.com/blog/2017/05/15/how-to-use-macstadium-and-gitlab-ci-to-build-your-macos-or-ios-projects/

However it is possible to run the Mac CI/CD directly if we have physical infrastructure already.

All of this would be essential for integration tests.

Alternatively there's the QEMU solution that we already use in the Matrix OS. This would be useful for distributed testing. This would utilise Nix as well:

* https://git.m-labs.hk/M-Labs/wfvm

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
