### ISSUE TITLE
Polykey GUI Framework

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#5]
We want Polykey frontends deployable on multiple platforms.

This is no longer updated, but demonstrates a simple application with the same codebase targeting mobile, web and desktop platforms: https://github.com/benoitvallon/react-native-nw-react-calculator

**Comment by robert-cronin** [comment]
Polykey will now use `vue.js` as its GUI framework. This foundations will be laid in the PR #43.
