### ISSUE TITLE
Add a structured log tracing system

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#51]
At the moment our logging output is unstructured output to the console. This can be improved by a log tracing system. Here are some ideas for libraries to use:

- [OpenTracing](https://opentracing.io/)
- [Jaeger](https://www.jaegertracing.io/) for visualising? 
- [LightStep](https://github.com/lightstep/lightstep-tracer-javascript)

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
