### ISSUE TITLE
.env file exposed on mvp branch

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#52]
For whatever reason, . gitignore doesn't include . env and this has led to my (free) twilio account credentials being exposed. This needs to be fixed ASAP and I will generate new tokens. Not really a big deal but could have been more serious. 
We can look forward to the day when the .env file is not needed and can be substituted with polykey secret injection.

**Comment by robert-cronin** [comment]
also an issue on master

**Comment by CMCDragonkai** [comment]
Lol. I just wrote an issue in our orientation about people making mistakes here. But the .env should always be ignored, that's why it's always in our demo repos. Is this your private twilio account?

**Comment by robert-cronin** [comment]
what good timing I have haha. 
Yeah i think the create-vuejs-project command  overwrote it. There is a lesson in here about not using external templates. 

Yeah it's just an account I created a few days ago for testing. No big deal in that sense.
