### ISSUE TITLE
MVP Target October 31st

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#53]
Current status 29th September 2020:

1. CA
2. OAuth2 (this is providing an HTTP integration)
3. Cleanup + NAT fixing
4. Polykey Desktop GUI
5. Integration into Ouroboros experiment
6. All the rest of existing issues that's labelled with the MVP milestone on the project board

Target is 31st October 2020.

**Comment by CMCDragonkai** [comment]
Once MVP here is done, development doesn't stop, but we start sales/marketing/grants/funding arrangements.

**Comment by CMCDragonkai** [comment]
I think @DrFacepalm can share some patterns from typescript-demo-spa into the GUI work from no onwards too.

**Comment by CMCDragonkai** [comment]
Updated milestone to match the target date.

**Comment by CMCDragonkai** [comment]
Current status!

1. ~~CA~~
2. ~~OAuth2 (this is providing an HTTP integration)~~
3. Cleanup + NAT fixing <- @robert-cronin is working on this atm: https://github.com/MatrixAI/js-polykey/pull/118
4. Polykey Desktop GUI <- @gideonairex  is working on this atm: #54
5. Integration into Ouroboros experiment <- @nzhang-zh is working on this
6. All the rest of existing issues that's labelled with the MVP milestone on the project board

By the 31st october, I'm pretty sure that we should have 3, 4, and 5 all done.

With respect to 4, that's just porting the existing interface (which was already written in vue 2...).

If we can, we can push it to even add in new UI designs. But to do that, we should back to the drawing board in Figma and look at all of the functionality that js-polykey provides (through the GRPC interface), and start thinking wireframes, and user flows of all of these functionality. This of course wouldn't be the 31st Oct target. But if we can get to this point, that would be great.

What we would like to see by 31st october is the a completely built Polykey electron app, that can be installed on our computers, we can dogfood it, and get initial feedback, and start iterating on the design.

The design process should be like this:

* Ideation/Drafting
* Wireframing in Figma
* Component creation - possibly facilitated by Storybook (when it supports vue3)
* And then to the actual application

During the ideation/drafting, that's when we can also consider how the components might transfer over to the nativescript/mobile UI and also the Matrix OS Convergence.

**Comment by gideonairex** [comment]
Current Updates

**Done**
1. ~~Was able to make it run on the local machine.~~
<img width="1277" alt="Screen Shot 2020-10-19 at 11 58 55 AM" src="https://user-images.githubusercontent.com/6386061/96400179-adcc1600-1202-11eb-9b05-202544209f47.png">

**Todo**
1. Update to vue 3.x
2. Update to vuex 4.x

**Approach**
1. Will run the app without backend for now and focus on the migration.

**Comment by gideonairex** [comment]
@CMCDragonkai 

so after running it in my local. There were issues in upgrading to vue3.

1. Had a roadblock on **vue-loader** as its being used in our compiler electron-webpack . This vue-loader is dependent on vue-template-compiler  https://github.com/electron-userland/electron-webpack/blob/5ad2481e1b90f3c290d4fa63879b9620f88887de/packages/electron-webpack/src/configurators/vue/vue.ts#L33. Had a work around here and used the latest webpack for electron https://github.com/nklayman/vue-cli-plugin-electron-builder
2. **vue-class-component** does not support vue3 **class** based and we have used **defineComponent** as an alternative which btw is much cleaner.
3. **vuetify** does not support vue3 yet and this is our UI Framework. https://vuetifyjs.com/en/introduction/roadmap/ . But I guess we can choose a different UI

Done:
1. was able to run the App.vue, Drawer.vue and AppBar.vue using vue3 now

Approach:
1. Lets not focus on the UI for now and just migrate it to vue3 and vuex4. Or we can choose a different UI for the time being just to see it while waiting for Vuetify? Anyways the UI is not yet final.

**Comment by robert-cronin** [comment]
I guess it doesn't have to look completely polished, as long as we can have a working prototype we can install on all our computers and start iterating with feedback from the matrix team.

I am aiming to have the PR sent off by either tomorrow afternoon or sometime on Monday, after that I can jump onto the app and build out the new backend part of the app that controls the pk agent. @gideonairex you could probably still keep going on the renderer while I do that and we can bring it all together in the latter part of the week 👍

**Comment by CMCDragonkai** [comment]
Yea it doesn't need to look polished. Just porting over existing interface, with targets of opportunity for adding features. Main thing is that the team can start using it.

On 23 October 2020 2:42:14 am AEDT, Robbie Cronin <notifications@github.com> wrote:
>I guess it doesn't have to look completely polished, as long as we can
>have a working prototype we can install on all our computers and start
>iterating with feedback from the matrix team.>
>>
>I am aiming to have the PR sent off by either tomorrow afternoon or
>sometime on Monday, after that I can jump onto the app and build out
>the new backend part of the app that controls the pk agent.
>@gideonairex you could probably still keep going on the renderer while
>I do that and we can bring it all together in the latter part of the
>week 👍 >
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/MatrixAI/PolyKey/issues/53#issuecomment-714582028

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
