### ISSUE TITLE
make multicast peer finding trigger-able

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Polykey-Desktop#57]
At the moment, the find function is not implemented in the gui (only on the cli).
The find command uses the multicast address to listen for broadcasts from other peers and this should be triggered automatically if the keynode is unable to find a peer on an old address but should also be trigger-able by the user.
Edit: this find function on the gui should also show the ip/port pair that the peer was found on.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
