### ISSUE TITLE
Integration Points - OS Keychain

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#6]
I'd like to get Polykey integrated as  part of OS keychains.

It could be an alternative keychain.

* D-Bus Secret Service
* Apple macOS keychain
* Microsoft Windows Credential Manager
* pass

Docker actually is capable of integrating into these keychains as you can see here: https://github.com/docker/docker-credential-helpers

This is interesting because it shows other applications delegating credential storage to a third party program rather than writing it themselves. I wonder if there's a standard for credential storage? Right now I've merged SSH key agent management with GNUPG agent, but these are still their own walled garden, with nothing else really integrating into that. Browsers maintain their own credentials, and every other system has their own as well.

**Comment by CMCDragonkai** [comment]
> By default, Docker looks for the native binary on each of the platforms, i.e. “osxkeychain” on macOS, “wincred” on windows, and “pass” on Linux. A special case is that on Linux, Docker will fall back to the “secretservice” binary if it cannot find the “pass” binary. If none of these binaries are present, it stores the credentials (i.e. password) in base64 encoding in the config files described above.
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store

This shows you that Docker login credentials are not even encrypted at rest.

**Comment by CMCDragonkai** [comment]
This appears to give us a way to standardise with freedesktop standards: https://lwn.net/Articles/490518/ @ll-aashwin-ll can you have a look to see if this model would help you develop the spec for the UI side of Polykey?

**Comment by CMCDragonkai** [comment]
Android and iOS are also important here. In fact Android and iOS integration I believe actually supersedes browser integration. So you don't really create a "browser plugin" for the mobile phone browsers, but a password manager can be integrated to the OS. For example: https://developer.android.com/guide/topics/text/autofill and https://developer.apple.com/documentation/security/password_autofill/

**Comment by CMCDragonkai** [comment]
This issue is will be split up into separate issues for different platforms. This is just research atm.

**Comment by CMCDragonkai** [comment]
For autofill/autotype on desktop, we should look at this:

* https://keepass.info/help/base/autotype.html
* https://keepass.info/help/v2/autotype_obfuscation.html
* https://community.bitwarden.com/t/auto-type-autofill-for-logging-into-other-desktop-apps/158/106 - see the last few comments describing some of this

I think desktops don't have a direct autofill/autotype feature builtin unlike mobile systems. But this would be quite useful for desktop applications.

**Comment by CMCDragonkai** [comment]
Since autofill is separate idea compared to os keychains. I've created a separate issue to #63.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
