### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#61]
We need to make sure that Polykey can be internationalised. Obviously start with US English. But subsequently most of the text can be swapped out with a language file.

I think there is a JS library designed for this.

Probably the next major language after English should be Chinese.

**Comment by CMCDragonkai** [comment]
https://phrase.com/blog/posts/the-best-javascript-i18n-libraries/

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
