### ISSUE TITLE
GUI Autofill/Autotype Integration

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#63]
For Desktop:

> For autofill/autotype on desktop, we should look at this:
> 
> * https://keepass.info/help/base/autotype.html
> * https://keepass.info/help/v2/autotype_obfuscation.html
> * https://community.bitwarden.com/t/auto-type-autofill-for-logging-into-other-desktop-apps/158/106 - see the last few comments describing some of this
> 
> I think desktops don't have a direct autofill/autotype feature builtin unlike mobile systems. But this would be quite useful for desktop applications.

For NativeScript:

> Android and iOS are also important here. In fact Android and iOS integration I believe actually supersedes browser integration. So you don't really create a "browser plugin" for the mobile phone browsers, but a password manager can be integrated to the OS. For example: https://developer.android.com/guide/topics/text/autofill and https://developer.apple.com/documentation/security/password_autofill/

**Comment by CMCDragonkai** [comment]
Beware of https://www.theverge.com/2017/12/30/16829804/browser-password-manager-adthink-princeton-research

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
