### ISSUE TITLE
Keynode Profile

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#64]
Keynodes are cryptographic entities that form part of the gestalt identity in cyberspace.

Each keynode entity has a public key, and thus has a public certificate.

An x509 certificate can contain custom information like how smallstep has encoded custom information on the certificates that they generation.

We can use this to encode further custom information while remaining standards compliant (and somehow combine both PGP and x509 together).

See: https://docs.gitlab.com/ee/user/project/repository/x509_signed_commits/

Although x509 and gpg are different protocols. They should have similar features to each other. I'm thinking we can do both as long as we choose one as the source protocol, and then generate the other based on the first. However I still don't have a straight answer if this is possible, @robert-cronin I think you have done some research here already. Hopefully you can comment on whether we are really using x509 or gpg for KN profiles, or the base protocol for crytographic operations in Polykey.

This issue is about designing how the Keynode Profile works. And this has relationship with:

* #41 
* #25 

And also remember the cryptofort avatar!

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
