### ISSUE TITLE
Typed Files (files with schema) in PolyKey

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Polykey-Desktop#9]
Right now we are just focusing on files inside Polykey being arbitrary.
But later one we should look into how to "type" the files inside a secret bundle and automatically generate an API on top of it. Sort of like HATEOAS but for filesystems/files or even like API specifications for these things. It should probably be extensible and it would be great if we could make use of OWL or RDF.

Consider a low priority for now.

Consider the idea of:

* https://www.gnu.org/software/recutils/

**Comment by CMCDragonkai** [comment]
This issue is about adding schema to the files that we can store in Polykey. This can aid the user to create structured data in Polykey. Such as a schema for credit card information, a schema for SSH keys, a schema for web username and password... Lastpass has similar things. Main point is that schemas are user created and configurable, so we have to represent our schemas as something that we can parse and then verify against a file. In effect, schemas have to be a bidirectional parser/generator.

Some notes... json schema is a schema used to verifying JSON documents. That would be OK, if all we are storing are JSON documents. But our Polykey can store arbitrary file content in arbitrary document structure.

**Comment by gideonairex** [comment]
Migrated to Gitlab closing this.
